### ISSUE TITLE
Data DOI

### ISSUE THREAD

**Issue by huard** [mzelinka/cmip56_forcing_feedback_ecs#1]
This is really useful and I'm using the data for a report I'm writing. I'm citing the paper already, but it would be nice to have a citation for the data as it evolved since publication.

There is a github action that publishes to Zenodo, which creates a DOI for each release. See
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by mzelinka** [comment]
Glad to hear it's useful!  The Zenodo link is [here](https://zenodo.org/record/6647291#.Y4DzMOzMIfg). The doi is https://doi.org/10.5281/zenodo.6647291

**Comment by huard** [comment]
Thanks!

**Comment by huard** [comment]
Au
